name: Bug report
description: Report a problem you encountered
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to complete this bug report!
  - type: checkboxes
    id: terms
    attributes:
      label: Guidelines
      description: By submitting this issue, you agree to follow our [Contributing Guidelines](https://github.com/Appsilon/.github/blob/main/CONTRIBUTING.md).
      options:
        - label: I agree to follow this project's Contributing Guidelines.
          required: true
  - type: input
    id: project
    attributes:
      label: Project Version
      description: Which project versions are affected?
      placeholder: "1.0, 2.2, 3.5.1"
    validations:
      required: false
  - type: input
    id: platform
    attributes:
      label: Platform and OS Version
      description: Which platforms or operating systems are affected?
      placeholder: "macOS 10.15.1, Ubuntu 20.04"
    validations:
      required: false
  - type: input
    id: existing-issues
    attributes:
      label: Existing Issues
      description: Are there any similar existing issues?
      placeholder: "#42"
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Clearly and concisely describe the bug.
      placeholder: Tell us what happened.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should have happened?
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: Please include code snippets, stack traces, or compiler errors.
      placeholder: Paste code snippets, stack traces, and compiler errors here
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: Add screenshots, gifs, or videos to help explain your problem.
      placeholder: Upload screenshots, gifs, and videos here
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other useful information about the problem here.
      placeholder: Is there any additional helpful information you can share?
    validations:
      required: false
